type User {
  uid: ID!
  username: String!
  email: String!
  createdAt: String!
}

type AuthPayload {
  token: String
  user: User
  error: AuthError
}

type AuthError {
  code: String!
  message: String!
}

input SignUpInput {
  username: String!
  email: String!
  password: String!
}

input SignInInput {
  identifier: String!
  password: String!
}

type Mutation {
  signup(input: SignUpInput!): AuthPayload!
  signin(input: SignInInput!): AuthPayload!
}
